### ISSUE TITLE
Run command for other attributes of kani like #[kani::solver(kissat)]`

### ISSUE THREAD

**Issue by jaisnan** [model-checking/kani-vscode-extension#30]
As of now, Kani attributes that aren't `unwind` and `proof` and a few more in a limited set aren't recognized and added to the command by the extension backend. While there isn't a Kani API yet, new features should be recognized by the extension.

**Comment by celinval** [comment]
Not sure I understand the issue. Can you give an example of what you're trying to solve?

**Comment by jaisnan** [comment]
Resolved by removing dependency on the vscode extension side.
