### ISSUE TITLE
Update `--visualize` to use `--enable-unstable` and throw a warning to the user

### ISSUE THREAD

**Issue by jaisnan** [model-checking/kani-vscode-extension#31]
As reported in https://github.com/model-checking/kani/issues/2048, the reports generated provide incorrect information sometimes. As this is provided as a main feature in the extension and part of the failure handling, a warning should be provided to the user about the reliability of using the `view report` button.

**Comment by celinval** [comment]
That's a great point! @adpaco-aws do you want to try to adapt the extension as part of the work?

**Comment by adpaco-aws** [comment]
According to the discussions we had last week regarding coverage, it sounds like the best path forward to provide coverage information through the extension is:
 1. Generate `gcov` coverage output from CBMC coverage information (see https://github.com/model-checking/kani/issues/1706)
 2. Change the `view report` button to a functionality that overlays the `gcov` output on the user's source code.

I'm not clear on the best way to proceed for (1). It could be as simple as producing `gcov` output from `cbmc-viewer` (or a fork of it), but we'd need to have end-to-end testing processes in any case.

**Comment by celinval** [comment]
@adpaco-aws those are great suggestions. This issue however only cover the change to include `--enable-unstable` when invoking `--visualize`. ☺️

**Comment by adpaco-aws** [comment]
Sorry, I misunderstood. Yes, I can take care of this issue.

**Comment by adpaco-aws** [comment]
Note: this is blocked at the moment because of #34

I could open a PR with changes not tested on the development version of Kani, but I'd rather wait and see if we can resolve #34 before.
