### ISSUE TITLE
Parsing the output while looking for path to report shouldn't rely on Python command

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani-vscode-extension#35]
The function `parseReportOutput` looks for the `python3` substring when searching for the path to the report. However, that string doesn't actually get printed unless you're executing VSCode in a remote machine. This is what the code in Kani looks like:

```rust
       if !self.args.quiet {
            println!("Report written to: {}/html/index.html", report_dir.to_string_lossy());
            warning("coverage information has been disabled for `--visualize` reports");
            // If using VS Code with Remote-SSH, suggest an option for remote viewing:
            if std::env::var("VSCODE_IPC_HOOK_CLI").is_ok()
                && std::env::var("SSH_CONNECTION").is_ok()
            {
                println!(
                    "VS Code automatically forwards ports for locally hosted servers. To view the report remotely,\nTry:  python3 -m http.server --directory {}/html",
                    report_dir.to_string_lossy()
                );
            }
        }
```

The extension feature should rely on the "Report written..." string instead.

**Comment by jaisnan** [comment]
Should move to using some sort of a structured and persistent output from Kani instead of output parsing. This problem is going to happen everytime there's a change to the output and that's not ideal.
