### ISSUE TITLE
Issue friendly error if the extension cannot execute Kani

### ISSUE THREAD

**Issue by celinval** [model-checking/kani-vscode-extension#72]
Screenshot or description of the issue: If the user installs the extension without installing Kani, running a proof will look like it is stuck in a loop.

I expected to see this happen: An error pop-up should show up saying that it couldn't execute Kani and that users should try to reinstall it in their system.

Instead, this happened: The test window will show a spinning wheel.

Link to PR / commit where the action failed: *link*

**Comment by jaisnan** [comment]
For this issue, we already store the file path to Kani in the user's environment. We'd just need to compare it to list of acceptable paths and versions and throw a pop similar to [how this issue](https://github.com/model-checking/kani-vscode-extension/issues/72) was resolved.

This is a good entry point for the issue - https://github.com/model-checking/kani-vscode-extension/blob/15c27c756b029833d126d12b4032b9c5aa1e6175/src/model/kaniRunner.ts#L33
