### ISSUE TITLE
Add caching option to improve activation time

### ISSUE THREAD

**Issue by jaisnan** [model-checking/kani-vscode-extension#8]
Screenshot or description of the issue: The extension parses and loads the test tree from scratch every time a window is opened. This can be avoided with simple caching.

I expected to see this happen: as soon as the extension is loaded, the test tree should be loaded from the context

Instead, this happened: Took time to parse the test tree again

Link to PR / commit where the action failed: #4

**Comment by jaisnan** [comment]
To expand, there is also a need to add caching of the results from the previous vscode instance. As of now, the user loses some of the information when they reload the window or when they close the window and reopen at a later time.

**Comment by adpaco-aws** [comment]
The extension is more efficient after #29
