### ISSUE TITLE
"Kani Executable crashed" error 

### ISSUE THREAD

**Issue by ChristopherRabotin** [model-checking/kani-vscode-extension#9]
Screenshot or description of the issue:

When starting a specific Kani proof from the "Testing" pane, VS Code reports that the extension has crashed without further information.

![Screenshot_20221220_180140](https://user-images.githubusercontent.com/4823784/208796094-007820eb-a457-49e5-ba03-d1f614b4237d.png)

![Screenshot_20221220_175959](https://user-images.githubusercontent.com/4823784/208796088-baf1c669-023d-4e24-a2f2-d40b67510db1.png)

The Extension Host logs haven't been too helpful for me so far:

![Screenshot_20221220_180036](https://user-images.githubusercontent.com/4823784/208796092-e28d2e33-cb81-4fe3-91f7-d2fc27096b3a.png)

I expected to see Kani run this specific proof.

Instead, the extension reported a crash.

This happens on this commit: https://github.com/nyx-space/hifitime/tree/5f3a5bb06172a5d7eee98530543ac18036126af2 .

Note that if I do `Ctrl+Shift+P` and `Kani: Run Cargo Kani` then all of the proof harnesses start correctly.

**Comment by jaisnan** [comment]
Thanks for the issue. The problem seems to come from the fact that single script kani fails on hifitime proofs due to unresolved import errors. A simple fix is to switch to using cargo kani on the proofs. For the extension logs too, I shall raise an issue as a generic "Kani crashed" message isn't that helpful. Thank you for bringing these to our notice.

**Comment by celinval** [comment]
Hi @jaisnan, have you created the issue to at least log the source of the crash reported by Kani?

**Comment by jaisnan** [comment]
This issue has been patched with the latest PR #14 . There are still some issues for cases where the proof is written under #[test] and #[kani::proof] and with the performance as well which is being worked on next, but the overall experience should be better (even if slightly slow for now).

**Comment by jaisnan** [comment]
![image](https://user-images.githubusercontent.com/91620234/212382999-414b926d-0b60-42fe-873f-7bee197dd0a4.png)

This is what it should look like to run all the proofs in the crate. Happy to take issues and would appreciate feature requests as well.
